# Generated by Django 5.1.4 on 2024-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
